// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH;

#nullable disable

namespace QLBH.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20240526165012_migration5")]
    partial class migration5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH.Models.Category", b =>
                {
                    b.Property<long>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1L,
                            CategoryName = "Laptop",
                            Order = 1,
                            Status = true
                        },
                        new
                        {
                            CategoryID = 2L,
                            CategoryName = "Màn hình",
                            Order = 4,
                            Status = true
                        },
                        new
                        {
                            CategoryID = 3L,
                            CategoryName = "Chuột",
                            Order = 2,
                            Status = true
                        },
                        new
                        {
                            CategoryID = 4L,
                            CategoryName = "Bàn phím",
                            Order = 3,
                            Status = true
                        });
                });

            modelBuilder.Entity("QLBH.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1L,
                            Address = "111/2 Lê Lợi, P5, Q1, TP. Hồ Chí Minh",
                            BirthDay = new DateTime(1990, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Lý Qua Cầu",
                            Email = "caulyqua@gmail.com",
                            Gender = false,
                            Phone = "0123456789",
                            Status = true
                        },
                        new
                        {
                            CustomerID = 2L,
                            Address = "2/10 Lý Thái Tổ, P1, Q2, TP. Hồ Chí Minh",
                            BirthDay = new DateTime(2000, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Trần Văn Sơn",
                            Email = "sontranvan@gmail.com",
                            Gender = true,
                            Phone = "0923456789",
                            Status = true
                        },
                        new
                        {
                            CustomerID = 3L,
                            Address = "9/2 Hoàng Diệu, P4, Q5, TP.Hồ Chí Minh",
                            BirthDay = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Hoàng Dược Thảo Mộc",
                            Email = "mochoangduocthao@gmail.com",
                            Phone = "0723456789",
                            Status = true
                        },
                        new
                        {
                            CustomerID = 4L,
                            Address = "666/3 Nguyễn Trãi, P1, Tân An,Long An",
                            BirthDay = new DateTime(1991, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Cao Thu Trang",
                            Email = "trangcaothu@gmail.com",
                            Gender = false,
                            Phone = "0623456789",
                            Status = true
                        },
                        new
                        {
                            CustomerID = 5L,
                            Address = "466/3 Nguyễn Du, P6, Gò Dầu, Tây Ninh",
                            BirthDay = new DateTime(1982, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Nguyễn Kiểu",
                            Email = "kieunguyen@gmail.com",
                            Gender = false,
                            Phone = "0823456789",
                            Status = true
                        });
                });

            modelBuilder.Entity("QLBH.Models.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderID"));

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("Date");

                    b.Property<TimeSpan>("OrderTime")
                        .HasColumnType("time");

                    b.Property<int>("ProgressID")
                        .HasColumnType("int");

                    b.Property<string>("ReceiveAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("Date");

                    b.Property<TimeSpan?>("ReceiveTime")
                        .HasColumnType("time");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProgressID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1L,
                            CustomerID = 1L,
                            EmployeeID = 1L,
                            OrderDate = new DateTime(2016, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTime = new TimeSpan(0, 16, 18, 30, 0),
                            ProgressID = 7,
                            ReceiveAddress = "1Z Cao Thắng, P1, Q1,TPHCM",
                            ReceiveDate = new DateTime(2016, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            OrderID = 2L,
                            CustomerID = 2L,
                            EmployeeID = 2L,
                            OrderDate = new DateTime(2016, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTime = new TimeSpan(0, 16, 40, 50, 0),
                            ProgressID = 7,
                            ReceiveAddress = "123N Lê Lai, P7,QPN, TPHCM",
                            ReceiveDate = new DateTime(2016, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            OrderID = 3L,
                            CustomerID = 3L,
                            EmployeeID = 1L,
                            OrderDate = new DateTime(2016, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTime = new TimeSpan(0, 17, 19, 12, 0),
                            ProgressID = 6,
                            ReceiveAddress = "345G Lê Lợi, P4, Q1, TP Mỹ Tho, Tiền Giang",
                            ReceiveDate = new DateTime(2016, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            OrderID = 4L,
                            CustomerID = 4L,
                            EmployeeID = 2L,
                            OrderDate = new DateTime(2017, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderTime = new TimeSpan(0, 7, 42, 19, 0),
                            ProgressID = 1,
                            ReceiveAddress = "1B Lý Thái Tổ, P2, TPHCM",
                            ReceiveDate = new DateTime(2017, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceiveTime = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("QLBH.Models.OrderDetail", b =>
                {
                    b.Property<long>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderDetailID"));

                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("QLBH.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageFile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MarketPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "1.png",
                            Price = 150.50m,
                            ProductName = "Laptop ToBaShi 12N4",
                            Quantity = 0,
                            Status = true
                        },
                        new
                        {
                            ProductID = 2L,
                            CategoryID = 1L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "2.png",
                            Price = 250.50m,
                            ProductName = "Laptop ShiBaCo N4T0",
                            Quantity = 15,
                            Status = true
                        },
                        new
                        {
                            ProductID = 3L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "3.png",
                            Price = 180.50m,
                            ProductName = "Lapto ToBaShi 12N5",
                            Quantity = 14,
                            Status = true
                        },
                        new
                        {
                            ProductID = 4L,
                            CategoryID = 1L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "4.png",
                            Price = 250.50m,
                            ProductName = "Laptop ShiBaCo N4T1",
                            Quantity = 13,
                            Status = true
                        },
                        new
                        {
                            ProductID = 5L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "5.png",
                            Price = 350.50m,
                            ProductName = "Laptop ToBaShi 12N6",
                            Quantity = 20,
                            Status = true
                        },
                        new
                        {
                            ProductID = 6L,
                            CategoryID = 1L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "6.png",
                            Price = 380.50m,
                            ProductName = "Laptop ShiBaCo N4T2",
                            Quantity = 40,
                            Status = true
                        },
                        new
                        {
                            ProductID = 7L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "7.png",
                            Price = 280.50m,
                            ProductName = "Laptop ToBaShi 12N7",
                            Quantity = 29,
                            Status = true
                        },
                        new
                        {
                            ProductID = 8L,
                            CategoryID = 1L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "8.png",
                            Price = 450.50m,
                            ProductName = "Laptop ShiBaCo N4T3",
                            Quantity = 30,
                            Status = true
                        },
                        new
                        {
                            ProductID = 9L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "9.png",
                            Price = 380.50m,
                            ProductName = "Laptop ToBaShi 12N8",
                            Quantity = 15,
                            Status = true
                        },
                        new
                        {
                            ProductID = 10L,
                            CategoryID = 1L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "10.png",
                            Price = 550.50m,
                            ProductName = "Laptop ShiBaCo N4T4",
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            ProductID = 11L,
                            CategoryID = 1L,
                            Description = "Chơi game tốt",
                            ImageFile = "11.png",
                            Price = 450.50m,
                            ProductName = "Laptop ToBaShi 12N9",
                            Quantity = 60,
                            Status = true
                        },
                        new
                        {
                            ProductID = 12L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "13.png",
                            Price = 50.50m,
                            ProductName = "Laptop hình ToBaShi 12N4",
                            Quantity = 4,
                            Status = true
                        },
                        new
                        {
                            ProductID = 14L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "14.png",
                            Price = 60.50m,
                            ProductName = "Màn hình ShiBaCo N4T0",
                            Quantity = 12,
                            Status = true
                        },
                        new
                        {
                            ProductID = 15L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "15.png",
                            Price = 60.50m,
                            ProductName = "Màn hình ToBaShi 12N5",
                            Quantity = 15,
                            Status = true
                        },
                        new
                        {
                            ProductID = 16L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "16.png",
                            Price = 70.50m,
                            ProductName = "Màn hình ShiBaCo N4T1",
                            Quantity = 14,
                            Status = true
                        },
                        new
                        {
                            ProductID = 17L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "17.png",
                            Price = 70.50m,
                            ProductName = "Màn hình ToBaShi 12N6",
                            Quantity = 26,
                            Status = true
                        },
                        new
                        {
                            ProductID = 18L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "18.png",
                            Price = 80.50m,
                            ProductName = "Màn hình ShiBaCo N4T2",
                            Quantity = 30,
                            Status = true
                        },
                        new
                        {
                            ProductID = 19L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "19.png",
                            Price = 80.50m,
                            ProductName = "Màn hình ToBaShi 12N7",
                            Quantity = 12,
                            Status = true
                        },
                        new
                        {
                            ProductID = 20L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "20.png",
                            Price = 90.50m,
                            ProductName = "Màn hình ShiBaCo N4T3",
                            Quantity = 10,
                            Status = true
                        },
                        new
                        {
                            ProductID = 21L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "21.png",
                            Price = 100.50m,
                            ProductName = "Màn hình ToBaShi 12N8",
                            Quantity = 12,
                            Status = true
                        },
                        new
                        {
                            ProductID = 22L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "22.png",
                            Price = 110.50m,
                            ProductName = "Màn hình ShiBaCo N4T4",
                            Quantity = 12,
                            Status = true
                        },
                        new
                        {
                            ProductID = 23L,
                            CategoryID = 2L,
                            Description = "Chơi game tốt",
                            ImageFile = "23.png",
                            Price = 110.50m,
                            ProductName = "Màn hình ToBaShi 12N9",
                            Quantity = 11,
                            Status = true
                        },
                        new
                        {
                            ProductID = 24L,
                            CategoryID = 2L,
                            Description = "Xử lý đồ họa tốt",
                            ImageFile = "24.png",
                            Price = 120.00m,
                            ProductName = "Màn hình ShiBaCo N4T5",
                            Quantity = 5,
                            Status = true
                        });
                });

            modelBuilder.Entity("QLBH.Models.Progress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<string>("ProgressName")
                        .IsRequired()
                        .HasColumnType("nchar(15)");

                    b.HasKey("ProgressID");

                    b.ToTable("Progresses");

                    b.HasData(
                        new
                        {
                            ProgressID = 1,
                            ProgressName = "New"
                        },
                        new
                        {
                            ProgressID = 2,
                            ProgressName = "Processing"
                        },
                        new
                        {
                            ProgressID = 3,
                            ProgressName = "Shipping"
                        },
                        new
                        {
                            ProgressID = 4,
                            ProgressName = "Canceled"
                        },
                        new
                        {
                            ProgressID = 5,
                            ProgressName = "Instalment"
                        },
                        new
                        {
                            ProgressID = 6,
                            ProgressName = "Failed"
                        },
                        new
                        {
                            ProgressID = 7,
                            ProgressName = "Completed"
                        });
                });

            modelBuilder.Entity("QLBH.Models.Order", b =>
                {
                    b.HasOne("QLBH.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.Models.Progress", "Progress")
                        .WithMany("Orders")
                        .HasForeignKey("ProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("QLBH.Models.OrderDetail", b =>
                {
                    b.HasOne("QLBH.Models.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLBH.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QLBH.Models.Product", b =>
                {
                    b.HasOne("QLBH.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QLBH.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QLBH.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QLBH.Models.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("QLBH.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("QLBH.Models.Progress", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
